name: Random_fact_generator
description: A Flutter app that generate random interesting facts using randomuselessfact API created for contest Flutter create.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:  ^0.12.0+2
  connectivity: ^0.4.2+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - graphics/