name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter pub run test
    - name: Flutter CLI
      uses: steebchen/flutter@v1.0.0
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
